[package]
name = "aoc2020_rust"
version = "0.1.0"
authors = ["Anupam Ashish Minz <anupamminz300am@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.3"
itertools = "0.10.0"
